# Site Settings
title:               Mellonise Down Under
tagline:             yet another travel blog ...
description:
baseurl:            "/blog"
url:                "https://phgo.github.io"
github:
  url:               "https://phgo.github.io/blog"
author:
  name:              "philipp goellner"
  email:             "philipp goellner@gmail.com"
  twitter:           "monhelm"
  github:            "phgo"
  facebook:          "100009724774686"
  linkedin:          "philipp-göllner-2b086a71"
navigation:
- title: Was soll das?
  url: /about
- title: Archiv
  url: /writing
- title: Kontakt
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
