# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:            "/blog"
url:                "https://phgo.github.io"
github:
  url:               "https://phgo.github.io/blog"
author:
  name:              "philipp goellner"
  email:             "philipp goellner@gmail.com"
  twitter:           "monhelm"
  instagram:         #"paululele"
  github:            "phgo"
  facebook:          "100009724774686"
  linkedin:          "philipp-göllner-2b086a71"
navigation:
- title: "About this blog ..."
  url: /about
- title: Blog Posts
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
